#!/usr/bin/env sh 

# midid - software MIDI synthesiser, utilising JACK
# Copyright (C) 2024  Jacob Sinclair <jcbsnclr@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


if [ $# -ne 1 ]; then
  echo "usage: $0 [NAME]"
  exit
fi

NAME="$(git config user.name)"
EMAIL="$(git config user.email)"
YEAR="$(date +%Y)"
FILE="$1"

function gpl() {
cat << EOF > $1
/*
 * midid - software MIDI synthesiser, utilising JACK
 * Copyright (C) $YEAR  $NAME <$EMAIL>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

EOF
}

gpl "source/$FILE.c"
gpl "source/$FILE.h"

echo "#pragma once" >> source/$FILE.h
echo "#include <$FILE.h>" >> source/$FILE.c
